#!/usr/bin/python

import os
import sys
from bottle import Bottle, TEMPLATE_PATH, view, static_file, error

virtenv = os.environ['APPDIR'] + '/virtenv/'
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.7/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')

TEMPLATE_PATH.append(os.path.join(os.environ['OPENSHIFT_REPO_DIR'], 'wsgi/views/'))
sys.path.append(os.path.join(os.getenv("OPENSHIFT_REPO_DIR"), "wsgi"))

try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

from mybottleapp import *
